{{- if and (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) (eq .Values.fsm.trafficInterceptionMode "NodeLevel") }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ printf "fsm-gateway-%s-%s" .Values.fsm.gateway.namespace .Values.fsm.gateway.name }}
  namespace: {{ .Values.fsm.gateway.namespace }}
  {{- if .Values.fsm.gateway.infrastructure }}
  {{- with .Values.fsm.gateway.infrastructure.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    {{- if .Values.fsm.gateway.infrastructure }}
    {{- with .Values.fsm.gateway.infrastructure.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    app: fsm-gateway
    gateway.flomesh.io/ns: {{ .Values.fsm.gateway.namespace }}
    gateway.flomesh.io/name: {{ .Values.fsm.gateway.name }}
    meshName: {{ .Values.fsm.meshName }}
spec:
  selector:
    matchLabels:
      app: fsm-gateway
      gateway.flomesh.io/ns: {{ .Values.fsm.gateway.namespace }}
      gateway.flomesh.io/name: {{ .Values.fsm.gateway.name }}
  template:
    metadata:
      labels:
        app: fsm-gateway
        gateway.flomesh.io/ns: {{ .Values.fsm.gateway.namespace }}
        gateway.flomesh.io/name: {{ .Values.fsm.gateway.name }}
        {{- with .Values.fsm.gateway.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.fsm.gateway.infrastructure }}
        {{- with .Values.fsm.gateway.infrastructure.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '59091'
        prometheus.io/path: '/metrics'
        {{- with .Values.fsm.gateway.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.fsm.gateway.infrastructure }}
        {{- with .Values.fsm.gateway.infrastructure.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
    spec:
      priorityClassName: system-node-critical
      initContainers:
      - name: wait-controller
        image: "{{ include "fsmCurl.image" . }}"
        imagePullPolicy: {{ .Values.fsm.image.pullPolicy }}
        command:
          - curl
          - {{ printf "http://fsm-controller.%s:9091/health/ready" .Values.fsm.fsmNamespace }}
          - --connect-timeout
          - "2"
          - --retry
          - "50"
          - --retry-connrefused
          - --retry-delay
          - "5"
        resources:
          {{- toYaml .Values.fsm.gateway.initResources | nindent 10 }}
        {{- with .Values.fsm.gateway.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      containers:
      - name: gateway
        image: localhost:5000/flomesh/pipy-nightly:latest
        imagePullPolicy: IfNotPresent
        ports:
          {{- range $listener := .Values.fsm.gateway.listeners }}
          - name: {{ $listener.name }}
            containerPort: {{ $listener.port }}
          {{- end }}
          - name: admin
            containerPort: 59091
        command:
          - pipy
          - -e
          - |
            pipy()
            .listen(15001)
            .serveHTTP(new Message('hi, it works as fgw1 outbound listener.\n'))
            .listen(15003)
            .serveHTTP(new Message('hi, it works as fgw1 inbound listener.\n'))
        resources:
          {{- toYaml .Values.fsm.gateway.resources | nindent 10 }}
        env:
        - name: FSM_NAMESPACE
          value: {{ .Values.fsm.fsmNamespace }}
        - name: FSM_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: FSM_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- with .Values.fsm.gateway.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.fsm.gateway.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        livenessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 5
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 59091
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 5
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 59091
      - image: localhost:5000/cybwan/curl
        imagePullPolicy: IfNotPresent
        name: curl
        command: [ "sleep", "365d" ]
      terminationGracePeriodSeconds: 60
      {{- with .Values.fsm.gateway.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fsm.gateway.serviceAccountName" . }}
      {{- with .Values.fsm.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fsm.gateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fsm.gateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}