{{- if .Values.fsm.fsmController.enablePodDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: fsm-controller-pdb
  namespace: {{ include "fsm.namespace" . }}
  labels:
    app: fsm-controller
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: fsm-controller
{{- end }}
