apiVersion: v1
kind: Service
metadata:
  name: fsm-injector
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-injector
spec:
  ports:
    - name: sidecar-inject
      port: 9090
  selector:
    app: fsm-injector