{{- if eq .Values.fsm.trafficInterceptionMode "NodeLevel" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fsm-xnetwork
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-xnetwork
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fsm-xnetwork
  template:
    metadata:
      labels:
        app: fsm-xnetwork
    spec:
      {{- if .Values.fsm.fsmXnetwork.affinity }}
      affinity:
      {{- toYaml .Values.fsm.fsmXnetwork.affinity | nindent 8 }}
      {{- end }}
      hostNetwork: true
      containers:
      - name: fsm-xnetwork
        image: "{{ include "fsmXnetmgmt.image" . }}"
        imagePullPolicy: {{ .Values.fsm.image.pullPolicy }}
        command: ['/app/fsm-xnetwork']
        args: [
          "--verbosity", "{{.Values.fsm.controllerLogLevel}}",
          "--fsm-namespace", "{{ include "fsm.namespace" . }}",
          "--fsm-version", "{{ .Chart.AppVersion }}",
          "--mesh-name", "{{.Values.fsm.meshName}}",
          "--trust-domain", "{{.Values.fsm.trustDomain}}",
        ]
        resources:
          limits:
            cpu: "{{.Values.fsm.fsmXnetwork.resource.limits.cpu}}"
            memory: "{{.Values.fsm.fsmXnetwork.resource.limits.memory}}"
          requests:
            cpu: "{{.Values.fsm.fsmXnetwork.resource.requests.cpu}}"
            memory: "{{.Values.fsm.fsmXnetwork.resource.requests.memory}}"
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /sys/fs/cgroup
            name: sys-fs-cgroup
          - mountPath: /host/opt/cni/bin
            name: cni-bin-dir
          - mountPath: /host/etc/cni/net.d
            name: cni-config-dir
          - mountPath: /host/proc
            name: host-proc
          - mountPath: /host/var/run
            name: host-var-run
            mountPropagation: Bidirectional
      dnsPolicy: ClusterFirst
      priorityClassName: system-node-critical
      restartPolicy: Always
      serviceAccountName: {{ .Release.Name }}
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
      volumes:
      - hostPath:
          path: /sys/fs/cgroup
        name: sys-fs-cgroup
      - hostPath:
          path: /proc
        name: host-proc
      - hostPath:
          path: /opt/cni/bin
        name: cni-bin-dir
      - hostPath:
          path: /etc/cni/net.d
        name: cni-config-dir
      - hostPath:
          path: /var/run
        name: host-var-run
{{- end }}