apiVersion: v1
kind: Service
metadata:
  name: fsm-validator
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-controller
spec:
  ports:
    - name: validator
      port: 9093
      targetPort: 9093
  selector:
    app: fsm-controller
