{{- if .Values.fsm.deployJaeger }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: jaeger
  name: jaeger
  namespace: {{ include "fsm.namespace" . }}

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: jaeger
  name: {{.Release.Name}}-jaeger

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Release.Name}}-jaeger
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: jaeger
subjects:
  - kind: ServiceAccount
    name: jaeger
    namespace: {{ include "fsm.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{.Release.Name}}-jaeger
  apiGroup: rbac.authorization.k8s.io
{{- end }}
