{{- if .Values.fsm.fluentBit.enableProxySupport }}
apiVersion: v1
kind: Secret
metadata:
  name: proxy-config
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
stringData:
  HTTP_PROXY: {{ .Values.fsm.fluentBit.httpProxy | quote }}
  HTTPS_PROXY: {{ .Values.fsm.fluentBit.httpsProxy | quote }}
{{- end }}
